[package]
name = "http_server"
version = "0.1.0"
authors = ["Ashvini Jangid <ashvinijangid@gmail.com>"]
edition = "2018"


[dependencies]
actix-web = "3.1.0"
actix-files = "0.4.0"
ansi_term = "0.12.1"
